// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

package com.haberdashervcs.server.protobuf;

public final class FilesProto {
  private FilesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ChangeType}
   */
  public enum ChangeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD = 0;</code>
     */
    ADD(0),
    /**
     * <code>MODIFY = 1;</code>
     */
    MODIFY(1),
    /**
     * <code>RENAME = 2;</code>
     */
    RENAME(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ADD = 0;</code>
     */
    public static final int ADD_VALUE = 0;
    /**
     * <code>MODIFY = 1;</code>
     */
    public static final int MODIFY_VALUE = 1;
    /**
     * <code>RENAME = 2;</code>
     */
    public static final int RENAME_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChangeType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ChangeType forNumber(int value) {
      switch (value) {
        case 0: return ADD;
        case 1: return MODIFY;
        case 2: return RENAME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChangeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChangeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChangeType>() {
            public ChangeType findValueByNumber(int number) {
              return ChangeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.haberdashervcs.server.protobuf.FilesProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChangeType[] VALUES = values();

    public static ChangeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChangeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ChangeType)
  }

  public interface FileEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes contents = 1;</code>
     * @return The contents.
     */
    com.google.protobuf.ByteString getContents();

    /**
     * <code>string commitId = 2;</code>
     * @return The commitId.
     */
    java.lang.String getCommitId();
    /**
     * <code>string commitId = 2;</code>
     * @return The bytes for commitId.
     */
    com.google.protobuf.ByteString
        getCommitIdBytes();

    /**
     * <code>.ChangeType changeType = 3;</code>
     * @return The enum numeric value on the wire for changeType.
     */
    int getChangeTypeValue();
    /**
     * <code>.ChangeType changeType = 3;</code>
     * @return The changeType.
     */
    com.haberdashervcs.server.protobuf.FilesProto.ChangeType getChangeType();
  }
  /**
   * Protobuf type {@code FileEntry}
   */
  public static final class FileEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileEntry)
      FileEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileEntry.newBuilder() to construct.
    private FileEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileEntry() {
      contents_ = com.google.protobuf.ByteString.EMPTY;
      commitId_ = "";
      changeType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              contents_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              commitId_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              changeType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.server.protobuf.FilesProto.FileEntry.class, com.haberdashervcs.server.protobuf.FilesProto.FileEntry.Builder.class);
    }

    public static final int CONTENTS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString contents_;
    /**
     * <code>bytes contents = 1;</code>
     * @return The contents.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContents() {
      return contents_;
    }

    public static final int COMMITID_FIELD_NUMBER = 2;
    private volatile java.lang.Object commitId_;
    /**
     * <code>string commitId = 2;</code>
     * @return The commitId.
     */
    @java.lang.Override
    public java.lang.String getCommitId() {
      java.lang.Object ref = commitId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitId_ = s;
        return s;
      }
    }
    /**
     * <code>string commitId = 2;</code>
     * @return The bytes for commitId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommitIdBytes() {
      java.lang.Object ref = commitId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANGETYPE_FIELD_NUMBER = 3;
    private int changeType_;
    /**
     * <code>.ChangeType changeType = 3;</code>
     * @return The enum numeric value on the wire for changeType.
     */
    @java.lang.Override public int getChangeTypeValue() {
      return changeType_;
    }
    /**
     * <code>.ChangeType changeType = 3;</code>
     * @return The changeType.
     */
    @java.lang.Override public com.haberdashervcs.server.protobuf.FilesProto.ChangeType getChangeType() {
      @SuppressWarnings("deprecation")
      com.haberdashervcs.server.protobuf.FilesProto.ChangeType result = com.haberdashervcs.server.protobuf.FilesProto.ChangeType.valueOf(changeType_);
      return result == null ? com.haberdashervcs.server.protobuf.FilesProto.ChangeType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!contents_.isEmpty()) {
        output.writeBytes(1, contents_);
      }
      if (!getCommitIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commitId_);
      }
      if (changeType_ != com.haberdashervcs.server.protobuf.FilesProto.ChangeType.ADD.getNumber()) {
        output.writeEnum(3, changeType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!contents_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, contents_);
      }
      if (!getCommitIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, commitId_);
      }
      if (changeType_ != com.haberdashervcs.server.protobuf.FilesProto.ChangeType.ADD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, changeType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.server.protobuf.FilesProto.FileEntry)) {
        return super.equals(obj);
      }
      com.haberdashervcs.server.protobuf.FilesProto.FileEntry other = (com.haberdashervcs.server.protobuf.FilesProto.FileEntry) obj;

      if (!getContents()
          .equals(other.getContents())) return false;
      if (!getCommitId()
          .equals(other.getCommitId())) return false;
      if (changeType_ != other.changeType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContents().hashCode();
      hash = (37 * hash) + COMMITID_FIELD_NUMBER;
      hash = (53 * hash) + getCommitId().hashCode();
      hash = (37 * hash) + CHANGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + changeType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.server.protobuf.FilesProto.FileEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileEntry)
        com.haberdashervcs.server.protobuf.FilesProto.FileEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.server.protobuf.FilesProto.FileEntry.class, com.haberdashervcs.server.protobuf.FilesProto.FileEntry.Builder.class);
      }

      // Construct using com.haberdashervcs.server.protobuf.FilesProto.FileEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contents_ = com.google.protobuf.ByteString.EMPTY;

        commitId_ = "";

        changeType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.server.protobuf.FilesProto.FileEntry getDefaultInstanceForType() {
        return com.haberdashervcs.server.protobuf.FilesProto.FileEntry.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.server.protobuf.FilesProto.FileEntry build() {
        com.haberdashervcs.server.protobuf.FilesProto.FileEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.server.protobuf.FilesProto.FileEntry buildPartial() {
        com.haberdashervcs.server.protobuf.FilesProto.FileEntry result = new com.haberdashervcs.server.protobuf.FilesProto.FileEntry(this);
        result.contents_ = contents_;
        result.commitId_ = commitId_;
        result.changeType_ = changeType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.server.protobuf.FilesProto.FileEntry) {
          return mergeFrom((com.haberdashervcs.server.protobuf.FilesProto.FileEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.server.protobuf.FilesProto.FileEntry other) {
        if (other == com.haberdashervcs.server.protobuf.FilesProto.FileEntry.getDefaultInstance()) return this;
        if (other.getContents() != com.google.protobuf.ByteString.EMPTY) {
          setContents(other.getContents());
        }
        if (!other.getCommitId().isEmpty()) {
          commitId_ = other.commitId_;
          onChanged();
        }
        if (other.changeType_ != 0) {
          setChangeTypeValue(other.getChangeTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.server.protobuf.FilesProto.FileEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.server.protobuf.FilesProto.FileEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString contents_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes contents = 1;</code>
       * @return The contents.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContents() {
        return contents_;
      }
      /**
       * <code>bytes contents = 1;</code>
       * @param value The contents to set.
       * @return This builder for chaining.
       */
      public Builder setContents(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes contents = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContents() {
        
        contents_ = getDefaultInstance().getContents();
        onChanged();
        return this;
      }

      private java.lang.Object commitId_ = "";
      /**
       * <code>string commitId = 2;</code>
       * @return The commitId.
       */
      public java.lang.String getCommitId() {
        java.lang.Object ref = commitId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commitId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string commitId = 2;</code>
       * @return The bytes for commitId.
       */
      public com.google.protobuf.ByteString
          getCommitIdBytes() {
        java.lang.Object ref = commitId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commitId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string commitId = 2;</code>
       * @param value The commitId to set.
       * @return This builder for chaining.
       */
      public Builder setCommitId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string commitId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommitId() {
        
        commitId_ = getDefaultInstance().getCommitId();
        onChanged();
        return this;
      }
      /**
       * <code>string commitId = 2;</code>
       * @param value The bytes for commitId to set.
       * @return This builder for chaining.
       */
      public Builder setCommitIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commitId_ = value;
        onChanged();
        return this;
      }

      private int changeType_ = 0;
      /**
       * <code>.ChangeType changeType = 3;</code>
       * @return The enum numeric value on the wire for changeType.
       */
      @java.lang.Override public int getChangeTypeValue() {
        return changeType_;
      }
      /**
       * <code>.ChangeType changeType = 3;</code>
       * @param value The enum numeric value on the wire for changeType to set.
       * @return This builder for chaining.
       */
      public Builder setChangeTypeValue(int value) {
        
        changeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ChangeType changeType = 3;</code>
       * @return The changeType.
       */
      @java.lang.Override
      public com.haberdashervcs.server.protobuf.FilesProto.ChangeType getChangeType() {
        @SuppressWarnings("deprecation")
        com.haberdashervcs.server.protobuf.FilesProto.ChangeType result = com.haberdashervcs.server.protobuf.FilesProto.ChangeType.valueOf(changeType_);
        return result == null ? com.haberdashervcs.server.protobuf.FilesProto.ChangeType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ChangeType changeType = 3;</code>
       * @param value The changeType to set.
       * @return This builder for chaining.
       */
      public Builder setChangeType(com.haberdashervcs.server.protobuf.FilesProto.ChangeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        changeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ChangeType changeType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChangeType() {
        
        changeType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileEntry)
    }

    // @@protoc_insertion_point(class_scope:FileEntry)
    private static final com.haberdashervcs.server.protobuf.FilesProto.FileEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.server.protobuf.FilesProto.FileEntry();
    }

    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileEntry>
        PARSER = new com.google.protobuf.AbstractParser<FileEntry>() {
      @java.lang.Override
      public FileEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.server.protobuf.FilesProto.FileEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013files.proto\"P\n\tFileEntry\022\020\n\010contents\030\001" +
      " \001(\014\022\020\n\010commitId\030\002 \001(\t\022\037\n\nchangeType\030\003 \001" +
      "(\0162\013.ChangeType*-\n\nChangeType\022\007\n\003ADD\020\000\022\n" +
      "\n\006MODIFY\020\001\022\n\n\006RENAME\020\002B2\n\"com.haberdashe" +
      "rvcs.server.protobufB\nFilesProtoP\000b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FileEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileEntry_descriptor,
        new java.lang.String[] { "Contents", "CommitId", "ChangeType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
