// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

package com.haberdashervcs.server.protobuf;

public final class FilesProto {
  private FilesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes contents = 1;</code>
     * @return The contents.
     */
    com.google.protobuf.ByteString getContents();
  }
  /**
   * Protobuf type {@code FileEntry}
   */
  public static final class FileEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileEntry)
      FileEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileEntry.newBuilder() to construct.
    private FileEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileEntry() {
      contents_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              contents_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.server.protobuf.FilesProto.FileEntry.class, com.haberdashervcs.server.protobuf.FilesProto.FileEntry.Builder.class);
    }

    public static final int CONTENTS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString contents_;
    /**
     * <code>bytes contents = 1;</code>
     * @return The contents.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContents() {
      return contents_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!contents_.isEmpty()) {
        output.writeBytes(1, contents_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!contents_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, contents_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.server.protobuf.FilesProto.FileEntry)) {
        return super.equals(obj);
      }
      com.haberdashervcs.server.protobuf.FilesProto.FileEntry other = (com.haberdashervcs.server.protobuf.FilesProto.FileEntry) obj;

      if (!getContents()
          .equals(other.getContents())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContents().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.server.protobuf.FilesProto.FileEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileEntry)
        com.haberdashervcs.server.protobuf.FilesProto.FileEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.server.protobuf.FilesProto.FileEntry.class, com.haberdashervcs.server.protobuf.FilesProto.FileEntry.Builder.class);
      }

      // Construct using com.haberdashervcs.server.protobuf.FilesProto.FileEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contents_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.server.protobuf.FilesProto.internal_static_FileEntry_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.server.protobuf.FilesProto.FileEntry getDefaultInstanceForType() {
        return com.haberdashervcs.server.protobuf.FilesProto.FileEntry.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.server.protobuf.FilesProto.FileEntry build() {
        com.haberdashervcs.server.protobuf.FilesProto.FileEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.server.protobuf.FilesProto.FileEntry buildPartial() {
        com.haberdashervcs.server.protobuf.FilesProto.FileEntry result = new com.haberdashervcs.server.protobuf.FilesProto.FileEntry(this);
        result.contents_ = contents_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.server.protobuf.FilesProto.FileEntry) {
          return mergeFrom((com.haberdashervcs.server.protobuf.FilesProto.FileEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.server.protobuf.FilesProto.FileEntry other) {
        if (other == com.haberdashervcs.server.protobuf.FilesProto.FileEntry.getDefaultInstance()) return this;
        if (other.getContents() != com.google.protobuf.ByteString.EMPTY) {
          setContents(other.getContents());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.server.protobuf.FilesProto.FileEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.server.protobuf.FilesProto.FileEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString contents_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes contents = 1;</code>
       * @return The contents.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContents() {
        return contents_;
      }
      /**
       * <code>bytes contents = 1;</code>
       * @param value The contents to set.
       * @return This builder for chaining.
       */
      public Builder setContents(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes contents = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContents() {
        
        contents_ = getDefaultInstance().getContents();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileEntry)
    }

    // @@protoc_insertion_point(class_scope:FileEntry)
    private static final com.haberdashervcs.server.protobuf.FilesProto.FileEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.server.protobuf.FilesProto.FileEntry();
    }

    public static com.haberdashervcs.server.protobuf.FilesProto.FileEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileEntry>
        PARSER = new com.google.protobuf.AbstractParser<FileEntry>() {
      @java.lang.Override
      public FileEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.server.protobuf.FilesProto.FileEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013files.proto\"\035\n\tFileEntry\022\020\n\010contents\030\001" +
      " \001(\014B2\n\"com.haberdashervcs.server.protob" +
      "ufB\nFilesProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FileEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileEntry_descriptor,
        new java.lang.String[] { "Contents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
