// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.haberdashervcs.common.protobuf;

public final class ServerProto {
  private ServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BranchAndCommitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BranchAndCommit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string branchName = 1;</code>
     * @return The branchName.
     */
    java.lang.String getBranchName();
    /**
     * <code>string branchName = 1;</code>
     * @return The bytes for branchName.
     */
    com.google.protobuf.ByteString
        getBranchNameBytes();

    /**
     * <code>int64 commitId = 2;</code>
     * @return The commitId.
     */
    long getCommitId();
  }
  /**
   * Protobuf type {@code BranchAndCommit}
   */
  public static final class BranchAndCommit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BranchAndCommit)
      BranchAndCommitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BranchAndCommit.newBuilder() to construct.
    private BranchAndCommit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BranchAndCommit() {
      branchName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BranchAndCommit();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BranchAndCommit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              branchName_ = s;
              break;
            }
            case 16: {

              commitId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haberdashervcs.common.protobuf.ServerProto.internal_static_BranchAndCommit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haberdashervcs.common.protobuf.ServerProto.internal_static_BranchAndCommit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit.class, com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit.Builder.class);
    }

    public static final int BRANCHNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object branchName_;
    /**
     * <code>string branchName = 1;</code>
     * @return The branchName.
     */
    @java.lang.Override
    public java.lang.String getBranchName() {
      java.lang.Object ref = branchName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        branchName_ = s;
        return s;
      }
    }
    /**
     * <code>string branchName = 1;</code>
     * @return The bytes for branchName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBranchNameBytes() {
      java.lang.Object ref = branchName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        branchName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMITID_FIELD_NUMBER = 2;
    private long commitId_;
    /**
     * <code>int64 commitId = 2;</code>
     * @return The commitId.
     */
    @java.lang.Override
    public long getCommitId() {
      return commitId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBranchNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, branchName_);
      }
      if (commitId_ != 0L) {
        output.writeInt64(2, commitId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBranchNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, branchName_);
      }
      if (commitId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, commitId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit)) {
        return super.equals(obj);
      }
      com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit other = (com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit) obj;

      if (!getBranchName()
          .equals(other.getBranchName())) return false;
      if (getCommitId()
          != other.getCommitId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRANCHNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBranchName().hashCode();
      hash = (37 * hash) + COMMITID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCommitId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BranchAndCommit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BranchAndCommit)
        com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haberdashervcs.common.protobuf.ServerProto.internal_static_BranchAndCommit_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haberdashervcs.common.protobuf.ServerProto.internal_static_BranchAndCommit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit.class, com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit.Builder.class);
      }

      // Construct using com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        branchName_ = "";

        commitId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haberdashervcs.common.protobuf.ServerProto.internal_static_BranchAndCommit_descriptor;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit getDefaultInstanceForType() {
        return com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit.getDefaultInstance();
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit build() {
        com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit buildPartial() {
        com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit result = new com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit(this);
        result.branchName_ = branchName_;
        result.commitId_ = commitId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit) {
          return mergeFrom((com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit other) {
        if (other == com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit.getDefaultInstance()) return this;
        if (!other.getBranchName().isEmpty()) {
          branchName_ = other.branchName_;
          onChanged();
        }
        if (other.getCommitId() != 0L) {
          setCommitId(other.getCommitId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object branchName_ = "";
      /**
       * <code>string branchName = 1;</code>
       * @return The branchName.
       */
      public java.lang.String getBranchName() {
        java.lang.Object ref = branchName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          branchName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string branchName = 1;</code>
       * @return The bytes for branchName.
       */
      public com.google.protobuf.ByteString
          getBranchNameBytes() {
        java.lang.Object ref = branchName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          branchName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string branchName = 1;</code>
       * @param value The branchName to set.
       * @return This builder for chaining.
       */
      public Builder setBranchName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        branchName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string branchName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBranchName() {
        
        branchName_ = getDefaultInstance().getBranchName();
        onChanged();
        return this;
      }
      /**
       * <code>string branchName = 1;</code>
       * @param value The bytes for branchName to set.
       * @return This builder for chaining.
       */
      public Builder setBranchNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        branchName_ = value;
        onChanged();
        return this;
      }

      private long commitId_ ;
      /**
       * <code>int64 commitId = 2;</code>
       * @return The commitId.
       */
      @java.lang.Override
      public long getCommitId() {
        return commitId_;
      }
      /**
       * <code>int64 commitId = 2;</code>
       * @param value The commitId to set.
       * @return This builder for chaining.
       */
      public Builder setCommitId(long value) {
        
        commitId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 commitId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommitId() {
        
        commitId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BranchAndCommit)
    }

    // @@protoc_insertion_point(class_scope:BranchAndCommit)
    private static final com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit();
    }

    public static com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BranchAndCommit>
        PARSER = new com.google.protobuf.AbstractParser<BranchAndCommit>() {
      @java.lang.Override
      public BranchAndCommit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BranchAndCommit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BranchAndCommit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BranchAndCommit> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.haberdashervcs.common.protobuf.ServerProto.BranchAndCommit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BranchAndCommit_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BranchAndCommit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\"7\n\017BranchAndCommit\022\022\n\nbra" +
      "nchName\030\001 \001(\t\022\020\n\010commitId\030\002 \001(\003B3\n\"com.h" +
      "aberdashervcs.common.protobufB\013ServerPro" +
      "toP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BranchAndCommit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BranchAndCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BranchAndCommit_descriptor,
        new java.lang.String[] { "BranchName", "CommitId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
