<html>
<head><title>Haberdasher: Login</title></head>

<body>
    <h3>Login</h3>

    <div id="formContainer">
        <form method="post" action="/login">
            <p>Username:</p><input type="text" id="usernameInput" name="username" />
            <p>Password:</p><input type="text" id="passwordInput" name="password" />
            <br/><input type="submit" value="Login" />
        </form>
    </div>

</body>
</html>
